apps:
    - script: ./run/app.js
      # 启用多少个实例，可用于负载均衡。如果-i 0或者-i max，则根据当前机器核数确定实例数目
      instances: 2
      # 监听应用目录的变化，一旦发生变化，自动重启。如果要精确监听、不见听的目录，最好通过配置文件。
      watch: true
      env:
          NODE_ENV: production
