version: "2"
services:
    mysql:
        image: mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=Ymslx-2020
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080